### PR TITLE
Fix: Skip lines with -i

### PR DESCRIPTION
**Pull request by glensc**
Fixes https://github.com/s0undt3ch/setuptools-declarative-requirements/issues/6

### CODE REVIEW

**Comment by glensc** [comment]
ping @s0undt3ch

**Comment by s0undt3ch** [comment]
Thank You!

**Comment by glensc** [comment]
I see 1.2.0 git tag created 1 hour ago, but this pr not included in changelog:
- https://github.com/s0undt3ch/setuptools-declarative-requirements/blob/1.2.0/CHANGELOG.md

and um, the 1.2.0 release date is set as 2020-12-19 there

also, `1.2.0` there links to https://pypi.org/project/setuptools-declarative-requirements/1.1.0/

**Comment by glensc** [comment]
pip also says 1.2.0 Released: Dec 19, 2020:
- https://pypi.org/project/setuptools-declarative-requirements/#history

so, fix this mess and then what version to install to get this ;)

**Comment by s0undt3ch** [comment]
All the published releases where previous tags which weren't published as releases on GirHub, but they were/are published to pypi.

Your fix will be on 1.3.0

**Pull request merged**
